# Generated by Django 5.1.2 on 2024-11-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_profiles/'),
        ),
    ]
