# Generated by Django 5.1.2 on 2024-11-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.TextField(),
        ),
    ]
