# Generated by Django 5.1.2 on 2024-11-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=50)),
            ],
        ),
    ]
