# Generated by Django 5.1.2 on 2024-11-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_freelancer_chatsession_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freelancer',
        ),
    ]
