# Generated by Django 5.1.2 on 2024-11-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_comment_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
