# Generated by Django 5.1.2 on 2024-11-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_post_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='done_by',
            field=models.IntegerField(default=0),
        ),
    ]
